ROCm 7.1 cherry-pick - Fixes and updates required for 7.1 (#663)
* Find package - rocdecode-host (#650)

* Find package - rocdecode-host

* Cleanup

---------

Co-authored-by: Kiriti <kiriti@santiago.amd.com>

* Docs - removing SP6 (#653)

* Packaging - Drop libva-amdgpu for RHEL 9+, Ubuntu 24, and SLES (#656)

* Drop libva-amdgpu for newer distros

Due to bugs in mixing old and new libva installed, having both
libva-amdgpu packages just causes bugs due to edge cases. It's easier
to just use the inbox packages for RHEL9+, SLE, and UB24.04.

RHEL 8 and UB22.04 still needs libva-amdgpu since libva is too old.

I also noticed that SLE should be pulling in libva-drm2 as a runtime
requirement, since rocdecode only uses the DRM interface.

SWDEV-555510
SWDEV-557842

Signed-off-by: Jeremy Newton <Jeremy.Newton@amd.com>

* rocDecode-setup.py - Fix

```
rocDecode-setup.py", line 246
    else
        ^
SyntaxError: expected ':'

```

* rocDecode-setup.py - Fix

```
rocDecode-setup.py", line 246
    else
        ^
SyntaxError: expected ':'

```

* rocDecode-setup.py - fix

```
E: Unable to locate package rocm-hip-runtime-devlibstdc++-12-dev
E: Couldn't find any package by regex 'rocm-hip-runtime-devlibstdc++-12-dev'

```

---------

Signed-off-by: Jeremy Newton <Jeremy.Newton@amd.com>
Co-authored-by: Kiriti Gowda <kiriti.nageshgowda@amd.com>

* Packaging - HIP Updates (#658)

* changelog update for PR658 (#659)

* Update changelog for ROCm 7.1 release (#661)

* ROCm 7.1 - updates (#662)

* Compiler - Location update (#664)

---------

Signed-off-by: Jeremy Newton <Jeremy.Newton@amd.com>
Co-authored-by: Kiriti <kiriti@santiago.amd.com>
Co-authored-by: spolifroni-amd <Sandra.Polifroni@amd.com>
Co-authored-by: Jeremy Newton <Mystro256@users.noreply.github.com>
Co-authored-by: Lakshmi Kumar <lakshmi.kumar@amd.com>
Co-authored-by: Aryan Salmanpour <aryan.salmanpour@amd.com>