Packaging - Drop libva-amdgpu for RHEL 9+, Ubuntu 24, and SLES (#656) (#657)
* Drop libva-amdgpu for newer distros

Due to bugs in mixing old and new libva installed, having both
libva-amdgpu packages just causes bugs due to edge cases. It's easier
to just use the inbox packages for RHEL9+, SLE, and UB24.04.

RHEL 8 and UB22.04 still needs libva-amdgpu since libva is too old.

I also noticed that SLE should be pulling in libva-drm2 as a runtime
requirement, since rocdecode only uses the DRM interface.

SWDEV-555510
SWDEV-557842



* rocDecode-setup.py - Fix

```
rocDecode-setup.py", line 246
    else
        ^
SyntaxError: expected ':'

```

* rocDecode-setup.py - Fix

```
rocDecode-setup.py", line 246
    else
        ^
SyntaxError: expected ':'

```

* rocDecode-setup.py - fix

```
E: Unable to locate package rocm-hip-runtime-devlibstdc++-12-dev
E: Couldn't find any package by regex 'rocm-hip-runtime-devlibstdc++-12-dev'

```

---------

Signed-off-by: Jeremy Newton <Jeremy.Newton@amd.com>
Co-authored-by: Jeremy Newton <Mystro256@users.noreply.github.com>